// DTE address catalogs: CAT-012 Departamento, CAT-013 Municipio, CAT-008 Distrito.
// Source: Ministerio de Hacienda / DGII, "Catálogos - Facturación Electrónica V1.1"
// (https://factura.gob.sv/informacion-tecnica-y-funcional/ → wpdmdl=5353).
// Every code is a 2-char zero-padded string; codes repeat across departments, so
// municipios/distritos are always looked up together with their departamento.

export interface DteAddressOption {
  codigo: string
  nombre: string
}

export interface DteMunicipioOption extends DteAddressOption {
  departamento: string
}

export interface DteDistritoOption extends DteAddressOption {
  departamento: string
  municipio: string
}

export const DTE_DEPARTAMENTOS: DteAddressOption[] = [
  { codigo: '00', nombre: 'Otro (Para extranjeros)' },
  { codigo: '01', nombre: 'Ahuachapán' },
  { codigo: '02', nombre: 'Santa Ana' },
  { codigo: '03', nombre: 'Sonsonate' },
  { codigo: '04', nombre: 'Chalatenango' },
  { codigo: '05', nombre: 'La Libertad' },
  { codigo: '06', nombre: 'San Salvador' },
  { codigo: '07', nombre: 'Cuscatlán' },
  { codigo: '08', nombre: 'La Paz' },
  { codigo: '09', nombre: 'Cabañas' },
  { codigo: '10', nombre: 'San Vicente' },
  { codigo: '11', nombre: 'Usulután' },
  { codigo: '12', nombre: 'San Miguel' },
  { codigo: '13', nombre: 'Morazán' },
  { codigo: '14', nombre: 'La Unión' },
]

export const DTE_MUNICIPIOS: DteMunicipioOption[] = [
  { codigo: '00', nombre: 'Otro (Para extranjeros)', departamento: '00' },
  { codigo: '13', nombre: 'AHUACHAPAN NORTE', departamento: '01' },
  { codigo: '14', nombre: 'AHUACHAPAN CENTRO', departamento: '01' },
  { codigo: '15', nombre: 'AHUACHAPAN SUR', departamento: '01' },
  { codigo: '14', nombre: 'SANTA ANA NORTE', departamento: '02' },
  { codigo: '15', nombre: 'SANTA ANA CENTRO', departamento: '02' },
  { codigo: '16', nombre: 'SANTA ANA ESTE', departamento: '02' },
  { codigo: '17', nombre: 'SANTA ANA OESTE', departamento: '02' },
  { codigo: '17', nombre: 'SONSONATE NORTE', departamento: '03' },
  { codigo: '18', nombre: 'SONSONATE CENTRO', departamento: '03' },
  { codigo: '19', nombre: 'SONSONATE ESTE', departamento: '03' },
  { codigo: '20', nombre: 'SONSONATE OESTE', departamento: '03' },
  { codigo: '34', nombre: 'CHALATENANGO NORTE', departamento: '04' },
  { codigo: '35', nombre: 'CHALATENANGO CENTRO', departamento: '04' },
  { codigo: '36', nombre: 'CHALATENANGO SUR', departamento: '04' },
  { codigo: '23', nombre: 'LA LIBERTAD NORTE', departamento: '05' },
  { codigo: '24', nombre: 'LA LIBERTAD CENTRO', departamento: '05' },
  { codigo: '25', nombre: 'LA LIBERTAD OESTE', departamento: '05' },
  { codigo: '26', nombre: 'LA LIBERTAD ESTE', departamento: '05' },
  { codigo: '27', nombre: 'LA LIBERTAD COSTA', departamento: '05' },
  { codigo: '28', nombre: 'LA LIBERTAD SUR', departamento: '05' },
  { codigo: '20', nombre: 'SAN SALVADOR NORTE', departamento: '06' },
  { codigo: '21', nombre: 'SAN SALVADOR OESTE', departamento: '06' },
  { codigo: '22', nombre: 'SAN SALVADOR ESTE', departamento: '06' },
  { codigo: '23', nombre: 'SAN SALVADOR CENTRO', departamento: '06' },
  { codigo: '24', nombre: 'SAN SALVADOR SUR', departamento: '06' },
  { codigo: '17', nombre: 'CUSCATLAN NORTE', departamento: '07' },
  { codigo: '18', nombre: 'CUSCATLAN SUR', departamento: '07' },
  { codigo: '23', nombre: 'LA PAZ OESTE', departamento: '08' },
  { codigo: '24', nombre: 'LA PAZ CENTRO', departamento: '08' },
  { codigo: '25', nombre: 'LA PAZ ESTE', departamento: '08' },
  { codigo: '10', nombre: 'CABAÑAS ESTE', departamento: '09' },
  { codigo: '11', nombre: 'CABAÑAS OESTE', departamento: '09' },
  { codigo: '14', nombre: 'SAN VICENTE NORTE', departamento: '10' },
  { codigo: '15', nombre: 'SAN VICENTE SUR', departamento: '10' },
  { codigo: '24', nombre: 'USULUTAN NORTE', departamento: '11' },
  { codigo: '25', nombre: 'USULUTAN ESTE', departamento: '11' },
  { codigo: '26', nombre: 'USULUTAN OESTE', departamento: '11' },
  { codigo: '21', nombre: 'SAN MIGUEL NORTE', departamento: '12' },
  { codigo: '22', nombre: 'SAN MIGUEL CENTRO', departamento: '12' },
  { codigo: '23', nombre: 'SAN MIGUEL OESTE', departamento: '12' },
  { codigo: '27', nombre: 'MORAZAN NORTE', departamento: '13' },
  { codigo: '28', nombre: 'MORAZAN SUR', departamento: '13' },
  { codigo: '19', nombre: 'LA UNION NORTE', departamento: '14' },
  { codigo: '20', nombre: 'LA UNION SUR', departamento: '14' },
]

export const DTE_DISTRITOS: DteDistritoOption[] = [
  { codigo: '00', nombre: 'Otro (Para extranjeros)', departamento: '00', municipio: '00' },
  { codigo: '01', nombre: 'AHUACHAPÁN', departamento: '01', municipio: '14' },
  { codigo: '02', nombre: 'APANECA', departamento: '01', municipio: '14' },
  { codigo: '03', nombre: 'ATIQUIZAYA', departamento: '01', municipio: '13' },
  { codigo: '04', nombre: 'CONCEPCIÓN DE ATACO', departamento: '01', municipio: '14' },
  { codigo: '05', nombre: 'EL REFUGIO', departamento: '01', municipio: '13' },
  { codigo: '06', nombre: 'GUAYMANGO', departamento: '01', municipio: '15' },
  { codigo: '07', nombre: 'JUJUTLA', departamento: '01', municipio: '15' },
  { codigo: '08', nombre: 'SAN FRANCISCO MENÉNDEZ', departamento: '01', municipio: '15' },
  { codigo: '09', nombre: 'SAN LORENZO', departamento: '01', municipio: '13' },
  { codigo: '10', nombre: 'SAN PEDRO PUXTLA', departamento: '01', municipio: '15' },
  { codigo: '11', nombre: 'TACUBA', departamento: '01', municipio: '14' },
  { codigo: '12', nombre: 'TURÍN', departamento: '01', municipio: '13' },
  { codigo: '01', nombre: 'CANDELARIA DE LA FRONTERA', departamento: '02', municipio: '17' },
  { codigo: '02', nombre: 'COATEPEQUE', departamento: '02', municipio: '16' },
  { codigo: '03', nombre: 'CHALCHUAPA', departamento: '02', municipio: '17' },
  { codigo: '04', nombre: 'EL CONGO', departamento: '02', municipio: '16' },
  { codigo: '05', nombre: 'EL PORVENIR', departamento: '02', municipio: '17' },
  { codigo: '06', nombre: 'MASAHUAT', departamento: '02', municipio: '14' },
  { codigo: '07', nombre: 'METAPÁN', departamento: '02', municipio: '14' },
  { codigo: '08', nombre: 'SAN ANTONIO PAJONAL', departamento: '02', municipio: '17' },
  { codigo: '09', nombre: 'SAN SEBASTIÁN SALITRILLO', departamento: '02', municipio: '17' },
  { codigo: '10', nombre: 'SANTA ANA', departamento: '02', municipio: '15' },
  { codigo: '11', nombre: 'STA ROSA GUACHI', departamento: '02', municipio: '14' },
  { codigo: '12', nombre: 'STGO D LA FRONT', departamento: '02', municipio: '17' },
  { codigo: '13', nombre: 'TEXISTEPEQUE', departamento: '02', municipio: '14' },
  { codigo: '01', nombre: 'ACAJUTLA', departamento: '03', municipio: '20' },
  { codigo: '02', nombre: 'ARMENIA', departamento: '03', municipio: '19' },
  { codigo: '03', nombre: 'CALUCO', departamento: '03', municipio: '19' },
  { codigo: '04', nombre: 'CUISNAHUAT', departamento: '03', municipio: '19' },
  { codigo: '05', nombre: 'STA I ISHUATAN', departamento: '03', municipio: '19' },
  { codigo: '06', nombre: 'IZALCO', departamento: '03', municipio: '19' },
  { codigo: '07', nombre: 'JUAYÚA', departamento: '03', municipio: '17' },
  { codigo: '08', nombre: 'NAHUIZALCO', departamento: '03', municipio: '17' },
  { codigo: '09', nombre: 'NAHULINGO', departamento: '03', municipio: '18' },
  { codigo: '10', nombre: 'SALCOATITÁN', departamento: '03', municipio: '17' },
  { codigo: '11', nombre: 'SAN ANTONIO DEL MONTE', departamento: '03', municipio: '18' },
  { codigo: '12', nombre: 'SAN JULIÁN', departamento: '03', municipio: '19' },
  { codigo: '13', nombre: 'STA C MASAHUAT', departamento: '03', municipio: '17' },
  { codigo: '14', nombre: 'SANTO DOMINGO GUZMÁN', departamento: '03', municipio: '18' },
  { codigo: '15', nombre: 'SONSONATE', departamento: '03', municipio: '18' },
  { codigo: '16', nombre: 'SONZACATE', departamento: '03', municipio: '18' },
  { codigo: '01', nombre: 'AGUA CALIENTE', departamento: '04', municipio: '35' },
  { codigo: '02', nombre: 'ARCATAO', departamento: '04', municipio: '36' },
  { codigo: '03', nombre: 'AZACUALPA', departamento: '04', municipio: '36' },
  { codigo: '04', nombre: 'CITALÁ', departamento: '04', municipio: '34' },
  { codigo: '05', nombre: 'COMALAPA', departamento: '04', municipio: '36' },
  { codigo: '06', nombre: 'CONCEPCIÓN QUEZALTEPEQUE', departamento: '04', municipio: '36' },
  { codigo: '07', nombre: 'CHALATENANGO', departamento: '04', municipio: '36' },
  { codigo: '08', nombre: 'DULCE NOM MARÍA', departamento: '04', municipio: '35' },
  { codigo: '09', nombre: 'EL CARRIZAL', departamento: '04', municipio: '36' },
  { codigo: '10', nombre: 'EL PARAÍSO', departamento: '04', municipio: '35' },
  { codigo: '11', nombre: 'LA LAGUNA', departamento: '04', municipio: '36' },
  { codigo: '12', nombre: 'LA PALMA', departamento: '04', municipio: '34' },
  { codigo: '13', nombre: 'LA REINA', departamento: '04', municipio: '35' },
  { codigo: '14', nombre: 'LAS VUELTAS', departamento: '04', municipio: '36' },
  { codigo: '15', nombre: 'NOMBRE DE JESUS', departamento: '04', municipio: '36' },
  { codigo: '16', nombre: 'NVA CONCEPCIÓN', departamento: '04', municipio: '35' },
  { codigo: '17', nombre: 'NUEVA TRINIDAD', departamento: '04', municipio: '36' },
  { codigo: '18', nombre: 'OJOS DE AGUA', departamento: '04', municipio: '36' },
  { codigo: '19', nombre: 'POTONICO', departamento: '04', municipio: '36' },
  { codigo: '20', nombre: 'SAN ANT LA CRUZ', departamento: '04', municipio: '36' },
  { codigo: '21', nombre: 'SAN ANT RANCHOS', departamento: '04', municipio: '36' },
  { codigo: '22', nombre: 'SAN FERNANDO', departamento: '04', municipio: '35' },
  { codigo: '23', nombre: 'SAN FRANCISCO LEMPA', departamento: '04', municipio: '36' },
  { codigo: '24', nombre: 'SAN FRANCISCO MORAZÁN', departamento: '04', municipio: '35' },
  { codigo: '25', nombre: 'SAN IGNACIO', departamento: '04', municipio: '34' },
  { codigo: '26', nombre: 'SAN I LABRADOR', departamento: '04', municipio: '36' },
  { codigo: '27', nombre: 'SAN J CANCASQUE', departamento: '04', municipio: '36' },
  { codigo: '28', nombre: 'SAN JOSE FLORES', departamento: '04', municipio: '36' },
  { codigo: '29', nombre: 'SAN LUIS CARMEN', departamento: '04', municipio: '36' },
  { codigo: '30', nombre: 'SN MIG MERCEDES', departamento: '04', municipio: '36' },
  { codigo: '31', nombre: 'SAN RAFAEL', departamento: '04', municipio: '35' },
  { codigo: '32', nombre: 'SANTA RITA', departamento: '04', municipio: '35' },
  { codigo: '33', nombre: 'TEJUTLA', departamento: '04', municipio: '35' },
  { codigo: '01', nombre: 'ANTGO CUSCATLÁN', departamento: '05', municipio: '26' },
  { codigo: '02', nombre: 'CIUDAD ARCE', departamento: '05', municipio: '24' },
  { codigo: '03', nombre: 'COLON', departamento: '05', municipio: '25' },
  { codigo: '04', nombre: 'COMASAGUA', departamento: '05', municipio: '28' },
  { codigo: '05', nombre: 'CHILTIUPAN', departamento: '05', municipio: '27' },
  { codigo: '06', nombre: 'HUIZÚCAR', departamento: '05', municipio: '26' },
  { codigo: '07', nombre: 'JAYAQUE', departamento: '05', municipio: '25' },
  { codigo: '08', nombre: 'JICALAPA', departamento: '05', municipio: '27' },
  { codigo: '09', nombre: 'LA LIBERTAD', departamento: '05', municipio: '27' },
  { codigo: '10', nombre: 'NUEVO CUSCATLÁN', departamento: '05', municipio: '26' },
  { codigo: '11', nombre: 'SANTA TECLA', departamento: '05', municipio: '28' },
  { codigo: '12', nombre: 'QUEZALTEPEQUE', departamento: '05', municipio: '23' },
  { codigo: '13', nombre: 'SACACOYO', departamento: '05', municipio: '25' },
  { codigo: '14', nombre: 'SN J VILLANUEVA', departamento: '05', municipio: '26' },
  { codigo: '15', nombre: 'SAN JUAN OPICO', departamento: '05', municipio: '24' },
  { codigo: '16', nombre: 'SAN MATÍAS', departamento: '05', municipio: '23' },
  { codigo: '17', nombre: 'SAN P TACACHICO', departamento: '05', municipio: '23' },
  { codigo: '18', nombre: 'TAMANIQUE', departamento: '05', municipio: '27' },
  { codigo: '19', nombre: 'TALNIQUE', departamento: '05', municipio: '25' },
  { codigo: '20', nombre: 'TEOTEPEQUE', departamento: '05', municipio: '27' },
  { codigo: '21', nombre: 'TEPECOYO', departamento: '05', municipio: '25' },
  { codigo: '22', nombre: 'ZARAGOZA', departamento: '05', municipio: '26' },
  { codigo: '01', nombre: 'AGUILARES', departamento: '06', municipio: '20' },
  { codigo: '02', nombre: 'APOPA', departamento: '06', municipio: '21' },
  { codigo: '03', nombre: 'AYUTUXTEPEQUE', departamento: '06', municipio: '23' },
  { codigo: '04', nombre: 'CUSCATANCINGO', departamento: '06', municipio: '23' },
  { codigo: '05', nombre: 'EL PAISNAL', departamento: '06', municipio: '20' },
  { codigo: '06', nombre: 'GUAZAPA', departamento: '06', municipio: '20' },
  { codigo: '07', nombre: 'ILOPANGO', departamento: '06', municipio: '22' },
  { codigo: '08', nombre: 'MEJICANOS', departamento: '06', municipio: '23' },
  { codigo: '09', nombre: 'NEJAPA', departamento: '06', municipio: '21' },
  { codigo: '10', nombre: 'PANCHIMALCO', departamento: '06', municipio: '24' },
  { codigo: '11', nombre: 'ROSARIO DE MORA', departamento: '06', municipio: '24' },
  { codigo: '12', nombre: 'SAN MARCOS', departamento: '06', municipio: '24' },
  { codigo: '13', nombre: 'SAN MARTIN', departamento: '06', municipio: '22' },
  { codigo: '14', nombre: 'SAN SALVADOR', departamento: '06', municipio: '23' },
  { codigo: '15', nombre: 'STG TEXACUANGOS', departamento: '06', municipio: '24' },
  { codigo: '16', nombre: 'SANTO TOMAS', departamento: '06', municipio: '24' },
  { codigo: '17', nombre: 'SOYAPANGO', departamento: '06', municipio: '22' },
  { codigo: '18', nombre: 'TONACATEPEQUE', departamento: '06', municipio: '22' },
  { codigo: '19', nombre: 'CIUDAD DELGADO', departamento: '06', municipio: '23' },
  { codigo: '01', nombre: 'CANDELARIA', departamento: '07', municipio: '18' },
  { codigo: '02', nombre: 'COJUTEPEQUE', departamento: '07', municipio: '18' },
  { codigo: '03', nombre: 'EL CARMEN', departamento: '07', municipio: '18' },
  { codigo: '04', nombre: 'EL ROSARIO', departamento: '07', municipio: '18' },
  { codigo: '05', nombre: 'MONTE SAN JUAN', departamento: '07', municipio: '18' },
  { codigo: '06', nombre: 'ORAT CONCEPCIÓN', departamento: '07', municipio: '17' },
  { codigo: '07', nombre: 'SAN B PERULAPIA', departamento: '07', municipio: '17' },
  { codigo: '08', nombre: 'SAN CRISTÓBAL', departamento: '07', municipio: '18' },
  { codigo: '09', nombre: 'SAN J GUAYABAL', departamento: '07', municipio: '17' },
  { codigo: '10', nombre: 'SAN P PERULAPÁN', departamento: '07', municipio: '17' },
  { codigo: '11', nombre: 'SAN RAF CEDROS', departamento: '07', municipio: '18' },
  { codigo: '12', nombre: 'SAN RAMON', departamento: '07', municipio: '18' },
  { codigo: '13', nombre: 'STA C ANALQUITO', departamento: '07', municipio: '18' },
  { codigo: '14', nombre: 'STA C MICHAPA', departamento: '07', municipio: '18' },
  { codigo: '15', nombre: 'SUCHITOTO', departamento: '07', municipio: '17' },
  { codigo: '16', nombre: 'TENANCINGO', departamento: '07', municipio: '18' },
  { codigo: '01', nombre: 'CUYULTITÁN', departamento: '08', municipio: '23' },
  { codigo: '02', nombre: 'EL ROSARIO', departamento: '08', municipio: '24' },
  { codigo: '03', nombre: 'JERUSALÉN', departamento: '08', municipio: '24' },
  { codigo: '04', nombre: 'MERCED LA CEIBA', departamento: '08', municipio: '24' },
  { codigo: '05', nombre: 'OLOCUILTA', departamento: '08', municipio: '23' },
  { codigo: '06', nombre: 'PARAÍSO OSORIO', departamento: '08', municipio: '24' },
  { codigo: '07', nombre: 'SN ANT MASAHUAT', departamento: '08', municipio: '24' },
  { codigo: '08', nombre: 'SAN EMIGDIO', departamento: '08', municipio: '24' },
  { codigo: '09', nombre: 'SN FCO CHINAMEC', departamento: '08', municipio: '23' },
  { codigo: '10', nombre: 'SAN J NONUALCO', departamento: '08', municipio: '25' },
  { codigo: '11', nombre: 'SAN JUAN TALPA', departamento: '08', municipio: '23' },
  { codigo: '12', nombre: 'SAN JUAN TEPEZONTES', departamento: '08', municipio: '24' },
  { codigo: '13', nombre: 'SAN LUIS TALPA', departamento: '08', municipio: '23' },
  { codigo: '14', nombre: 'SAN MIGUEL TEPEZONTES', departamento: '08', municipio: '24' },
  { codigo: '15', nombre: 'SAN PEDRO MASAHUAT', departamento: '08', municipio: '23' },
  { codigo: '16', nombre: 'SAN PEDRO NONUALCO', departamento: '08', municipio: '24' },
  { codigo: '17', nombre: 'SAN R OBRAJUELO', departamento: '08', municipio: '25' },
  { codigo: '18', nombre: 'STA MA OSTUMA', departamento: '08', municipio: '24' },
  { codigo: '19', nombre: 'STGO NONUALCO', departamento: '08', municipio: '24' },
  { codigo: '20', nombre: 'TAPALHUACA', departamento: '08', municipio: '23' },
  { codigo: '21', nombre: 'ZACATECOLUCA', departamento: '08', municipio: '25' },
  { codigo: '22', nombre: 'SN LUIS LA HERR', departamento: '08', municipio: '24' },
  { codigo: '01', nombre: 'CINQUERA', departamento: '09', municipio: '11' },
  { codigo: '02', nombre: 'GUACOTECTI', departamento: '09', municipio: '10' },
  { codigo: '03', nombre: 'ILOBASCO', departamento: '09', municipio: '11' },
  { codigo: '04', nombre: 'JUTIAPA', departamento: '09', municipio: '11' },
  { codigo: '05', nombre: 'SAN ISIDRO', departamento: '09', municipio: '10' },
  { codigo: '06', nombre: 'SENSUNTEPEQUE', departamento: '09', municipio: '10' },
  { codigo: '07', nombre: 'TEJUTEPEQUE', departamento: '09', municipio: '11' },
  { codigo: '08', nombre: 'VICTORIA', departamento: '09', municipio: '10' },
  { codigo: '09', nombre: 'DOLORES', departamento: '09', municipio: '10' },
  { codigo: '01', nombre: 'APASTEPEQUE', departamento: '10', municipio: '14' },
  { codigo: '02', nombre: 'GUADALUPE', departamento: '10', municipio: '15' },
  { codigo: '03', nombre: 'SAN CAY ISTEPEQ', departamento: '10', municipio: '15' },
  { codigo: '04', nombre: 'SANTA CLARA', departamento: '10', municipio: '14' },
  { codigo: '05', nombre: 'SANTO DOMINGO', departamento: '10', municipio: '14' },
  { codigo: '06', nombre: 'SN EST CATARINA', departamento: '10', municipio: '14' },
  { codigo: '07', nombre: 'SAN ILDEFONSO', departamento: '10', municipio: '14' },
  { codigo: '08', nombre: 'SAN LORENZO', departamento: '10', municipio: '14' },
  { codigo: '09', nombre: 'SAN SEBASTIÁN', departamento: '10', municipio: '14' },
  { codigo: '10', nombre: 'SAN VICENTE', departamento: '10', municipio: '15' },
  { codigo: '11', nombre: 'TECOLUCA', departamento: '10', municipio: '15' },
  { codigo: '12', nombre: 'TEPETITÁN', departamento: '10', municipio: '15' },
  { codigo: '13', nombre: 'VERAPAZ', departamento: '10', municipio: '15' },
  { codigo: '01', nombre: 'ALEGRÍA', departamento: '11', municipio: '24' },
  { codigo: '02', nombre: 'BERLÍN', departamento: '11', municipio: '24' },
  { codigo: '03', nombre: 'CALIFORNIA', departamento: '11', municipio: '25' },
  { codigo: '04', nombre: 'CONCEP BATRES', departamento: '11', municipio: '25' },
  { codigo: '05', nombre: 'EL TRIUNFO', departamento: '11', municipio: '24' },
  { codigo: '06', nombre: 'EREGUAYQUÍN', departamento: '11', municipio: '25' },
  { codigo: '07', nombre: 'ESTANZUELAS', departamento: '11', municipio: '24' },
  { codigo: '08', nombre: 'JIQUILISCO', departamento: '11', municipio: '26' },
  { codigo: '09', nombre: 'JUCUAPA', departamento: '11', municipio: '24' },
  { codigo: '10', nombre: 'JUCUARÁN', departamento: '11', municipio: '25' },
  { codigo: '11', nombre: 'MERCEDES UMAÑA', departamento: '11', municipio: '24' },
  { codigo: '12', nombre: 'NUEVA GRANADA', departamento: '11', municipio: '24' },
  { codigo: '13', nombre: 'OZATLÁN', departamento: '11', municipio: '25' },
  { codigo: '14', nombre: 'PTO EL TRIUNFO', departamento: '11', municipio: '26' },
  { codigo: '15', nombre: 'SAN AGUSTÍN', departamento: '11', municipio: '26' },
  { codigo: '16', nombre: 'SN BUENAVENTURA', departamento: '11', municipio: '24' },
  { codigo: '17', nombre: 'SAN DIONISIO', departamento: '11', municipio: '25' },
  { codigo: '18', nombre: 'SANTA ELENA', departamento: '11', municipio: '25' },
  { codigo: '19', nombre: 'SAN FCO JAVIER', departamento: '11', municipio: '26' },
  { codigo: '20', nombre: 'SANTA MARÍA', departamento: '11', municipio: '25' },
  { codigo: '21', nombre: 'STGO DE MARÍA', departamento: '11', municipio: '24' },
  { codigo: '22', nombre: 'TECAPÁN', departamento: '11', municipio: '25' },
  { codigo: '23', nombre: 'USULUTÁN', departamento: '11', municipio: '25' },
  { codigo: '01', nombre: 'CAROLINA', departamento: '12', municipio: '21' },
  { codigo: '02', nombre: 'CIUDAD BARRIOS', departamento: '12', municipio: '21' },
  { codigo: '03', nombre: 'COMACARÁN', departamento: '12', municipio: '22' },
  { codigo: '04', nombre: 'CHAPELTIQUE', departamento: '12', municipio: '21' },
  { codigo: '05', nombre: 'CHINAMECA', departamento: '12', municipio: '23' },
  { codigo: '06', nombre: 'CHIRILAGUA', departamento: '12', municipio: '22' },
  { codigo: '07', nombre: 'EL TRANSITO', departamento: '12', municipio: '23' },
  { codigo: '08', nombre: 'LOLOTIQUE', departamento: '12', municipio: '23' },
  { codigo: '09', nombre: 'MONCAGUA', departamento: '12', municipio: '22' },
  { codigo: '10', nombre: 'NUEVA GUADALUPE', departamento: '12', municipio: '23' },
  { codigo: '11', nombre: 'NVO EDÉN S JUAN', departamento: '12', municipio: '21' },
  { codigo: '12', nombre: 'QUELEPA', departamento: '12', municipio: '22' },
  { codigo: '13', nombre: 'SAN ANT D MOSCO', departamento: '12', municipio: '21' },
  { codigo: '14', nombre: 'SAN GERARDO', departamento: '12', municipio: '21' },
  { codigo: '15', nombre: 'SAN JORGE', departamento: '12', municipio: '23' },
  { codigo: '16', nombre: 'SAN LUIS REINA', departamento: '12', municipio: '21' },
  { codigo: '17', nombre: 'SAN MIGUEL', departamento: '12', municipio: '22' },
  { codigo: '18', nombre: 'SAN RAF ORIENTE', departamento: '12', municipio: '23' },
  { codigo: '19', nombre: 'SESORI', departamento: '12', municipio: '21' },
  { codigo: '20', nombre: 'ULUAZAPA', departamento: '12', municipio: '22' },
  { codigo: '01', nombre: 'ARAMBALA', departamento: '13', municipio: '27' },
  { codigo: '02', nombre: 'CACAOPERA', departamento: '13', municipio: '27' },
  { codigo: '03', nombre: 'CORINTO', departamento: '13', municipio: '27' },
  { codigo: '04', nombre: 'CHILANGA', departamento: '13', municipio: '28' },
  { codigo: '05', nombre: 'DELIC DE CONCEP', departamento: '13', municipio: '28' },
  { codigo: '06', nombre: 'EL DIVISADERO', departamento: '13', municipio: '28' },
  { codigo: '07', nombre: 'EL ROSARIO', departamento: '13', municipio: '27' },
  { codigo: '08', nombre: 'GUALOCOCTI', departamento: '13', municipio: '28' },
  { codigo: '09', nombre: 'GUATAJIAGUA', departamento: '13', municipio: '28' },
  { codigo: '10', nombre: 'JOATECA', departamento: '13', municipio: '27' },
  { codigo: '11', nombre: 'JOCOAITIQUE', departamento: '13', municipio: '27' },
  { codigo: '12', nombre: 'JOCORO', departamento: '13', municipio: '28' },
  { codigo: '13', nombre: 'LOLOTIQUILLO', departamento: '13', municipio: '28' },
  { codigo: '14', nombre: 'MEANGUERA', departamento: '13', municipio: '27' },
  { codigo: '15', nombre: 'OSICALA', departamento: '13', municipio: '28' },
  { codigo: '16', nombre: 'PERQUÍN', departamento: '13', municipio: '27' },
  { codigo: '17', nombre: 'SAN CARLOS', departamento: '13', municipio: '28' },
  { codigo: '18', nombre: 'SAN FERNANDO', departamento: '13', municipio: '27' },
  { codigo: '19', nombre: 'SAN FCO GOTERA', departamento: '13', municipio: '28' },
  { codigo: '20', nombre: 'SAN ISIDRO', departamento: '13', municipio: '27' },
  { codigo: '21', nombre: 'SAN SIMÓN', departamento: '13', municipio: '28' },
  { codigo: '22', nombre: 'SENSEMBRA', departamento: '13', municipio: '28' },
  { codigo: '23', nombre: 'SOCIEDAD', departamento: '13', municipio: '28' },
  { codigo: '24', nombre: 'TOROLA', departamento: '13', municipio: '27' },
  { codigo: '25', nombre: 'YAMABAL', departamento: '13', municipio: '28' },
  { codigo: '26', nombre: 'YOLOAIQUÍN', departamento: '13', municipio: '28' },
  { codigo: '01', nombre: 'ANAMOROS', departamento: '14', municipio: '19' },
  { codigo: '02', nombre: 'BOLÍVAR', departamento: '14', municipio: '19' },
  { codigo: '03', nombre: 'CONCEP DE OTE', departamento: '14', municipio: '19' },
  { codigo: '04', nombre: 'CONCHAGUA', departamento: '14', municipio: '20' },
  { codigo: '05', nombre: 'EL CARMEN', departamento: '14', municipio: '20' },
  { codigo: '06', nombre: 'EL SAUCE', departamento: '14', municipio: '19' },
  { codigo: '07', nombre: 'INTIPUCÁ', departamento: '14', municipio: '20' },
  { codigo: '08', nombre: 'LA UNIÓN', departamento: '14', municipio: '20' },
  { codigo: '09', nombre: 'LISLIQUE', departamento: '14', municipio: '19' },
  { codigo: '10', nombre: 'MEANG DEL GOLFO', departamento: '14', municipio: '20' },
  { codigo: '11', nombre: 'NUEVA ESPARTA', departamento: '14', municipio: '19' },
  { codigo: '12', nombre: 'PASAQUINA', departamento: '14', municipio: '19' },
  { codigo: '13', nombre: 'POLORÓS', departamento: '14', municipio: '19' },
  { codigo: '14', nombre: 'SAN ALEJO', departamento: '14', municipio: '20' },
  { codigo: '15', nombre: 'SAN JOSE', departamento: '14', municipio: '19' },
  { codigo: '16', nombre: 'SANTA ROSA LIMA', departamento: '14', municipio: '19' },
  { codigo: '17', nombre: 'YAYANTIQUE', departamento: '14', municipio: '20' },
  { codigo: '18', nombre: 'YUCUAIQUÍN', departamento: '14', municipio: '20' },
]

export const dteMunicipiosFor = (departamento: string): DteMunicipioOption[] =>
  DTE_MUNICIPIOS.filter((m) => m.departamento === departamento)

export const dteDistritosFor = (
  departamento: string,
  municipio: string,
): DteDistritoOption[] =>
  DTE_DISTRITOS.filter((d) => d.departamento === departamento && d.municipio === municipio)

export const dteOptionLabel = (option: DteAddressOption): string =>
  `${option.codigo} · ${option.nombre}`

// A saved code that is not in the catalog (stale/foreign value) is kept as an
// option so a select never silently blanks and re-saves it as empty.
export const dteOptionsWithCurrent = (
  options: DteAddressOption[],
  current: string,
): DteAddressOption[] =>
  current && !options.some((o) => o.codigo === current)
    ? [{ codigo: current, nombre: current }, ...options]
    : options
