// Code generated by translator; DO NOT EDIT.

export const SCHEMA_UUID = "80591db756917b3780cf0cae8c29c25b"

export const FULL_DDL = `CREATE TABLE IF NOT EXISTS "admin" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "user_name" TEXT NOT NULL,
    "first_name" TEXT,
    "last_name" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "password_hash" TEXT NOT NULL,
    "last_login_date_time" TEXT,
    "login_tries" INTEGER DEFAULT 0,
    "mute" INTEGER DEFAULT 1 NOT NULL,
    "time_stamp" TEXT DEFAULT CURRENT_TIMESTAMP,
    "silent_print" INTEGER DEFAULT 0 NOT NULL,
    "kitchen_location_group_printer_uuid" TEXT,
    "guest_location_group_printer_uuid" TEXT,
    "is_owner" INTEGER DEFAULT 0 NOT NULL,
    UNIQUE ("user_name"),
    FOREIGN KEY ("guest_location_group_printer_uuid") REFERENCES "location_group_printer" ("uuid"),
    FOREIGN KEY ("kitchen_location_group_printer_uuid") REFERENCES "location_group_printer" ("uuid")
);

CREATE TABLE IF NOT EXISTS "admin_balance_history" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "admin_uuid" TEXT NOT NULL,
    "time_stamp" TEXT DEFAULT CURRENT_TIMESTAMP,
    "balance_whole" INTEGER DEFAULT 0 NOT NULL,
    "balance_hundredths" INTEGER DEFAULT 0 NOT NULL,
    "add" INTEGER DEFAULT 1,
    "confirmation_code" TEXT,
    "confirmed" INTEGER DEFAULT 0,
    FOREIGN KEY ("admin_uuid") REFERENCES "admin" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "admin_location" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "admin_uuid" TEXT NOT NULL,
    "owner" INTEGER DEFAULT 0,
    "location_group_uuid" TEXT NOT NULL,
    UNIQUE ("admin_uuid"),
    FOREIGN KEY ("admin_uuid") REFERENCES "admin" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "admin_location_permission" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "admin_location_uuid" TEXT NOT NULL,
    "permission_uuid" TEXT NOT NULL,
    FOREIGN KEY ("admin_location_uuid") REFERENCES "admin_location" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("permission_uuid") REFERENCES "permission" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "admin_push_creds" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "admin_uuid" TEXT NOT NULL,
    "endpoint" TEXT NOT NULL,
    "p256dh" TEXT NOT NULL,
    "auth" TEXT NOT NULL,
    UNIQUE ("admin_uuid"),
    FOREIGN KEY ("admin_uuid") REFERENCES "admin" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "bogo_menu_item" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "bogo_uuid" TEXT NOT NULL,
    "menu_item_uuid" TEXT NOT NULL,
    FOREIGN KEY ("menu_item_uuid") REFERENCES "menu_item" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "combo" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "active" INTEGER DEFAULT 1,
    "location_group_uuid" TEXT NOT NULL,
    "price_whole" INTEGER NOT NULL,
    "price_hundredths" INTEGER NOT NULL,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "combo_menu_item" (
    "combo_uuid" TEXT NOT NULL,
    "menu_item_uuid" TEXT NOT NULL,
    "minimum_amount" INTEGER DEFAULT 0 NOT NULL,
    UNIQUE ("combo_uuid", "menu_item_uuid"),
    FOREIGN KEY ("combo_uuid") REFERENCES "combo" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("menu_item_uuid") REFERENCES "menu_item" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "country" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "nombre" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "iso2" TEXT NOT NULL,
    "iso3" TEXT NOT NULL,
    "phonecode" INTEGER,
    "language_uuid" TEXT,
    FOREIGN KEY ("language_uuid") REFERENCES "language" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "dining_table" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT,
    "active" INTEGER,
    "location_group_uuid" TEXT NOT NULL,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "environment" (
    "name" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "feature" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "self_serve" INTEGER NOT NULL,
    "price_whole" INTEGER DEFAULT 0 NOT NULL,
    "price_hundredths" INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS "fulfillment" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "guest" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "user_name" TEXT NOT NULL,
    "first_name" TEXT,
    "last_name" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "password_hash" TEXT,
    "last_login_date_time" TEXT,
    "login_tries" INTEGER DEFAULT 0,
    UNIQUE ("user_name")
);

CREATE TABLE IF NOT EXISTS "guest_address" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "address" TEXT NOT NULL,
    "guest_uuid" TEXT NOT NULL,
    FOREIGN KEY ("guest_uuid") REFERENCES "guest" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "guest_location_group" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "guest_uuid" TEXT NOT NULL,
    "location_group_uuid" TEXT NOT NULL,
    "points" INTEGER DEFAULT 0 NOT NULL,
    UNIQUE ("location_group_uuid", "guest_uuid"),
    FOREIGN KEY ("guest_uuid") REFERENCES "guest" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "guest_push_creds" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "guest_uuid" TEXT,
    "app_unique_uuid" TEXT,
    "endpoint" TEXT NOT NULL,
    "p256dh" TEXT NOT NULL,
    "auth" TEXT NOT NULL,
    FOREIGN KEY ("guest_uuid") REFERENCES "guest" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "key_value" (
    "key" TEXT NOT NULL PRIMARY KEY,
    "value" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "language" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "nombre" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "lets_encrypt" (
    "name" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "location_group" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description1" TEXT,
    "description2" TEXT,
    "description3" TEXT,
    "description4" TEXT,
    "url_name" TEXT,
    "phone" TEXT,
    "address" TEXT,
    "city" TEXT,
    "ticket_description" TEXT,
    "theme" INTEGER DEFAULT 0 NOT NULL,
    "time_stamp" TEXT DEFAULT CURRENT_TIMESTAMP,
    "qr_code" TEXT,
    "tip_percentage" INTEGER DEFAULT 0 NOT NULL,
    "country_uuid" TEXT DEFAULT 'e56e26df-5232-434d-ac1b-4cf1c3e48a9f' NOT NULL,
    "day_price_cents" INTEGER DEFAULT 17 NOT NULL,
    "simple_print" INTEGER DEFAULT 1 NOT NULL,
    "print_notes" INTEGER DEFAULT 1 NOT NULL,
    "tax_percentage" INTEGER DEFAULT 0 NOT NULL,
    UNIQUE ("url_name"),
    FOREIGN KEY ("country_uuid") REFERENCES "country" ("uuid")
);

CREATE TABLE IF NOT EXISTS "location_group_activation_history" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "location_group_uuid" TEXT NOT NULL,
    "time_stamp" TEXT DEFAULT CURRENT_TIMESTAMP,
    "active" INTEGER DEFAULT 1,
    "day_price_cents" INTEGER DEFAULT 17 NOT NULL,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "location_group_feature" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "location_group_uuid" TEXT NOT NULL,
    "feature_uuid" TEXT NOT NULL,
    "time_stamp" TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("feature_uuid") REFERENCES "feature" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "location_group_printer" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "width_millimeters" INTEGER NOT NULL,
    "location_group_uuid" TEXT NOT NULL,
    "printer_type_uuid" TEXT NOT NULL,
    "host" TEXT,
    "port" INTEGER,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("printer_type_uuid") REFERENCES "printer_type" ("uuid")
);

CREATE TABLE IF NOT EXISTS "location_group_schema_version" (
    "location_group_uuid" TEXT NOT NULL PRIMARY KEY,
    "version" INTEGER DEFAULT 1 NOT NULL,
    "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "log" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "level" TEXT,
    "id" TEXT,
    "status" TEXT,
    "req" TEXT,
    "type" TEXT,
    "path" TEXT,
    "file" TEXT,
    "data" TEXT,
    "ms" TEXT
);

CREATE TABLE IF NOT EXISTS "menu" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "active" INTEGER DEFAULT 1,
    "sh0" INTEGER,
    "sm0" INTEGER,
    "st0" TEXT,
    "eh0" INTEGER,
    "em0" INTEGER,
    "et0" TEXT,
    "sh1" INTEGER,
    "sm1" INTEGER,
    "st1" TEXT,
    "eh1" INTEGER,
    "em1" INTEGER,
    "et1" TEXT,
    "sh2" INTEGER,
    "sm2" INTEGER,
    "st2" TEXT,
    "eh2" INTEGER,
    "em2" INTEGER,
    "et2" TEXT,
    "sh3" INTEGER,
    "sm3" INTEGER,
    "st3" TEXT,
    "eh3" INTEGER,
    "em3" INTEGER,
    "et3" TEXT,
    "sh4" INTEGER,
    "sm4" INTEGER,
    "st4" TEXT,
    "eh4" INTEGER,
    "em4" INTEGER,
    "et4" TEXT,
    "sh5" INTEGER,
    "sm5" INTEGER,
    "st5" TEXT,
    "eh5" INTEGER,
    "em5" INTEGER,
    "et5" TEXT,
    "sh6" INTEGER,
    "sm6" INTEGER,
    "st6" TEXT,
    "eh6" INTEGER,
    "em6" INTEGER,
    "et6" TEXT,
    "location_group_uuid" TEXT NOT NULL,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "menu_category" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "active" INTEGER DEFAULT 1,
    "location_group_uuid" TEXT NOT NULL,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "menu_combo" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "menu_uuid" TEXT NOT NULL,
    "combo_uuid" TEXT NOT NULL,
    UNIQUE ("menu_uuid", "combo_uuid"),
    FOREIGN KEY ("combo_uuid") REFERENCES "combo" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("menu_uuid") REFERENCES "menu" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "menu_item" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT,
    "description" TEXT,
    "active" INTEGER DEFAULT 1,
    "complete" INTEGER DEFAULT 0,
    "price_whole" INTEGER NOT NULL,
    "price_hundredths" INTEGER NOT NULL,
    "location_group_uuid" TEXT NOT NULL,
    "cache" TEXT NOT NULL,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "menu_item_menu_category" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "menu_item_uuid" TEXT NOT NULL,
    "menu_category_uuid" TEXT NOT NULL,
    UNIQUE ("menu_item_uuid", "menu_category_uuid"),
    FOREIGN KEY ("menu_category_uuid") REFERENCES "menu_category" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("menu_item_uuid") REFERENCES "menu_item" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "menu_item_modifier_group" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "modifier_group_uuid" TEXT NOT NULL,
    "menu_item_uuid" TEXT NOT NULL,
    UNIQUE ("menu_item_uuid"),
    FOREIGN KEY ("menu_item_uuid") REFERENCES "menu_item" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("modifier_group_uuid") REFERENCES "modifier_group" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "menu_menu_category" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "menu_uuid" TEXT NOT NULL,
    "menu_category_uuid" TEXT NOT NULL,
    UNIQUE ("menu_uuid", "menu_category_uuid"),
    FOREIGN KEY ("menu_category_uuid") REFERENCES "menu_category" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("menu_uuid") REFERENCES "menu" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "mock_schema_sync_probe" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "label" TEXT,
    "created_at" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS "modifier" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "active" INTEGER DEFAULT 1,
    "price_whole" INTEGER DEFAULT 0 NOT NULL,
    "price_hundredths" INTEGER DEFAULT 0 NOT NULL,
    "limit" INTEGER DEFAULT 0 NOT NULL,
    "location_group_uuid" TEXT NOT NULL,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "modifier_group" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "amount_required" INTEGER NOT NULL,
    "location_group_uuid" TEXT NOT NULL,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "modifier_group_modifier" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "modifier_group_uuid" TEXT NOT NULL,
    "modifier_uuid" TEXT NOT NULL,
    UNIQUE ("modifier_group_uuid", "modifier_uuid"),
    FOREIGN KEY ("modifier_uuid") REFERENCES "modifier" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("modifier_group_uuid") REFERENCES "modifier_group" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "payment" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "permission" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "print_record" (
    "ticket_uuid" TEXT NOT NULL PRIMARY KEY,
    "decision" TEXT DEFAULT 'pending' NOT NULL,
    "printed_at" INTEGER,
    "synced" INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS "printer_type" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "type" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "promotion" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "type" TEXT NOT NULL,
    "active" INTEGER DEFAULT 1 NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "auto_apply" INTEGER DEFAULT 1 NOT NULL,
    "promotion_is_percentage" INTEGER DEFAULT 0 NOT NULL,
    "location_group_uuid" TEXT NOT NULL,
    "discount_percent" INTEGER,
    "discount_whole" INTEGER,
    "discount_hundredths" INTEGER,
    "points_required" INTEGER,
    "points_earnable" INTEGER,
    "points_multiplier" INTEGER DEFAULT 0 NOT NULL,
    "items_required" INTEGER,
    "minimum_purchase_whole" INTEGER,
    "minimum_purchase_hundredths" INTEGER,
    "bogo_buy" TEXT,
    "bogo_buy_items_ammount" INTEGER,
    "bogo_get" TEXT,
    "bogo_get_items_ammount" INTEGER,
    "all_week" INTEGER DEFAULT 1 NOT NULL,
    "mon" INTEGER DEFAULT 0 NOT NULL,
    "tue" INTEGER DEFAULT 0 NOT NULL,
    "wed" INTEGER DEFAULT 0 NOT NULL,
    "thu" INTEGER DEFAULT 0 NOT NULL,
    "fri" INTEGER DEFAULT 0 NOT NULL,
    "sat" INTEGER DEFAULT 0 NOT NULL,
    "sun" INTEGER DEFAULT 0 NOT NULL,
    "monday_start_time" INTEGER,
    "monday_end_time" INTEGER,
    "tuesday_start_time" INTEGER,
    "tuesday_end_time" INTEGER,
    "wednesday_start_time" INTEGER,
    "wednesday_end_time" INTEGER,
    "thursday_start_time" INTEGER,
    "thursday_end_time" INTEGER,
    "friday_start_time" INTEGER,
    "friday_end_time" INTEGER,
    "saturday_start_time" INTEGER,
    "saturday_end_time" INTEGER,
    "sunday_start_time" INTEGER,
    "sunday_end_time" INTEGER,
    "redeemptions_per_visit" INTEGER,
    "redeemptions_per_day" INTEGER,
    "redeemptions_per_week" INTEGER,
    "redeemptions_per_month" INTEGER,
    "redeemptions_all_time" INTEGER,
    "minimum_total_tickets" INTEGER,
    "combinable" INTEGER DEFAULT 0 NOT NULL,
    "all_items" INTEGER DEFAULT 1 NOT NULL,
    "all_categories" INTEGER DEFAULT 1 NOT NULL,
    "itemless" INTEGER DEFAULT 0 NOT NULL,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "session" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "entity_uuid" TEXT NOT NULL,
    "entity_type" TEXT NOT NULL,
    "time_stamp" TEXT DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "sub_category" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "parent_uuid" TEXT NOT NULL,
    "menu_category_uuid" TEXT NOT NULL,
    "location_group_uuid" TEXT NOT NULL,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("menu_category_uuid") REFERENCES "menu_category" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "sub_category_menu_item" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "sub_category_uuid" TEXT NOT NULL,
    "menu_item_uuid" TEXT NOT NULL,
    UNIQUE ("sub_category_uuid", "menu_item_uuid"),
    FOREIGN KEY ("menu_item_uuid") REFERENCES "menu_item" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("sub_category_uuid") REFERENCES "sub_category" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ticket" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "id" INTEGER NOT NULL,
    "time_stamp" TEXT DEFAULT CURRENT_TIMESTAMP,
    "status" TEXT,
    "guest_uuid" TEXT,
    "app_unique_uuid" TEXT,
    "table_uuid" TEXT,
    "location_group_uuid" TEXT NOT NULL,
    "fulfillment_uuid" TEXT,
    "guest_address_uuid" TEXT,
    "admin_uuid" TEXT,
    "anonymous_address" TEXT,
    "price_whole" INTEGER,
    "price_hundredths" INTEGER,
    "is_dirty" INTEGER DEFAULT 0 NOT NULL,
    "is_local" INTEGER DEFAULT 0 NOT NULL,
    FOREIGN KEY ("admin_uuid") REFERENCES "admin" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("fulfillment_uuid") REFERENCES "fulfillment" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("guest_address_uuid") REFERENCES "guest_address" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("guest_uuid") REFERENCES "guest" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("location_group_uuid") REFERENCES "location_group" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("table_uuid") REFERENCES "dining_table" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ticket_log" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "location_group_uuid" TEXT NOT NULL,
    "ticket_uuid" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "payload" TEXT NOT NULL,
    "time_stamp" INTEGER NOT NULL,
    "admin_uuid" TEXT
);

CREATE TABLE IF NOT EXISTS "ticket_log_applied" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "time_stamp" TEXT,
    "retry_count" INTEGER DEFAULT 0,
    "last_error" TEXT,
    "next_retry_at" INTEGER
);

CREATE TABLE IF NOT EXISTS "ticket_menu_item" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "ticket_uuid" TEXT NOT NULL,
    "menu_item_uuid" TEXT NOT NULL,
    "note" TEXT,
    FOREIGN KEY ("menu_item_uuid") REFERENCES "menu_item" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("ticket_uuid") REFERENCES "ticket" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ticket_menu_item_modifier" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "ticket_uuid" TEXT NOT NULL,
    "modifier_uuid" TEXT NOT NULL,
    "ticket_menu_item_uuid" TEXT NOT NULL,
    "time_stamp" TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("modifier_uuid") REFERENCES "modifier" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("ticket_menu_item_uuid") REFERENCES "ticket_menu_item" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("ticket_uuid") REFERENCES "ticket" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ticket_payment" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "ticket_uuid" TEXT NOT NULL,
    "payment_uuid" TEXT NOT NULL,
    "price_whole" INTEGER NOT NULL,
    "price_hundredths" INTEGER NOT NULL,
    "code" TEXT,
    "complete" INTEGER DEFAULT 0,
    FOREIGN KEY ("payment_uuid") REFERENCES "payment" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("ticket_uuid") REFERENCES "ticket" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ticket_print" (
    "ticket_uuid" TEXT NOT NULL PRIMARY KEY,
    "claimed_at" TEXT,
    "printed_at" TEXT,
    "claimed_by" TEXT,
    FOREIGN KEY ("ticket_uuid") REFERENCES "ticket" ("uuid") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ticket_promotion" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "time_stamp" TEXT DEFAULT CURRENT_TIMESTAMP,
    "ticket_uuid" TEXT NOT NULL,
    "promotion_uuid" TEXT NOT NULL,
    "ticket_menu_item_uuid" TEXT,
    UNIQUE ("ticket_menu_item_uuid"),
    FOREIGN KEY ("promotion_uuid") REFERENCES "promotion" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("ticket_menu_item_uuid") REFERENCES "ticket_menu_item" ("uuid") ON DELETE CASCADE,
    FOREIGN KEY ("ticket_uuid") REFERENCES "ticket" ("uuid") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "idx_admin_guest_location_group_printer_uuid" ON "admin" ("guest_location_group_printer_uuid");

CREATE INDEX IF NOT EXISTS "idx_admin_kitchen_location_group_printer_uuid" ON "admin" ("kitchen_location_group_printer_uuid");

CREATE INDEX IF NOT EXISTS "idx_admin_balance_history_admin_uuid" ON "admin_balance_history" ("admin_uuid");

CREATE INDEX IF NOT EXISTS "idx_admin_location_admin_uuid" ON "admin_location" ("admin_uuid");

CREATE INDEX IF NOT EXISTS "idx_admin_location_location_group_uuid" ON "admin_location" ("location_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_admin_location_permission_admin_location_uuid" ON "admin_location_permission" ("admin_location_uuid");

CREATE INDEX IF NOT EXISTS "idx_admin_location_permission_permission_uuid" ON "admin_location_permission" ("permission_uuid");

CREATE INDEX IF NOT EXISTS "idx_admin_push_creds_admin_uuid" ON "admin_push_creds" ("admin_uuid");

CREATE INDEX IF NOT EXISTS "idx_bogo_menu_item_menu_item_uuid" ON "bogo_menu_item" ("menu_item_uuid");

CREATE INDEX IF NOT EXISTS "idx_combo_location_group_uuid" ON "combo" ("location_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_combo_menu_item_combo_uuid" ON "combo_menu_item" ("combo_uuid");

CREATE INDEX IF NOT EXISTS "idx_combo_menu_item_menu_item_uuid" ON "combo_menu_item" ("menu_item_uuid");

CREATE INDEX IF NOT EXISTS "idx_country_language_uuid" ON "country" ("language_uuid");

CREATE INDEX IF NOT EXISTS "idx_dining_table_location_group_uuid" ON "dining_table" ("location_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_guest_address_guest_uuid" ON "guest_address" ("guest_uuid");

CREATE INDEX IF NOT EXISTS "idx_guest_location_group_guest_uuid" ON "guest_location_group" ("guest_uuid");

CREATE INDEX IF NOT EXISTS "idx_guest_location_group_location_group_uuid" ON "guest_location_group" ("location_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_guest_push_creds_guest_uuid" ON "guest_push_creds" ("guest_uuid");

CREATE INDEX IF NOT EXISTS "idx_location_group_country_uuid" ON "location_group" ("country_uuid");

CREATE INDEX IF NOT EXISTS "idx_location_group_activation_history_location_group_uuid" ON "location_group_activation_history" ("location_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_location_group_feature_feature_uuid" ON "location_group_feature" ("feature_uuid");

CREATE INDEX IF NOT EXISTS "idx_location_group_feature_location_group_uuid" ON "location_group_feature" ("location_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_location_group_printer_location_group_uuid" ON "location_group_printer" ("location_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_location_group_printer_printer_type_uuid" ON "location_group_printer" ("printer_type_uuid");

CREATE INDEX IF NOT EXISTS "idx_menu_location_group_uuid" ON "menu" ("location_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_menu_category_location_group_uuid" ON "menu_category" ("location_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_menu_combo_combo_uuid" ON "menu_combo" ("combo_uuid");

CREATE INDEX IF NOT EXISTS "idx_menu_combo_menu_uuid" ON "menu_combo" ("menu_uuid");

CREATE INDEX IF NOT EXISTS "idx_menu_item_location_group_uuid" ON "menu_item" ("location_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_menu_item_menu_category_menu_category_uuid" ON "menu_item_menu_category" ("menu_category_uuid");

CREATE INDEX IF NOT EXISTS "idx_menu_item_menu_category_menu_item_uuid" ON "menu_item_menu_category" ("menu_item_uuid");

CREATE INDEX IF NOT EXISTS "idx_menu_item_modifier_group_menu_item_uuid" ON "menu_item_modifier_group" ("menu_item_uuid");

CREATE INDEX IF NOT EXISTS "idx_menu_item_modifier_group_modifier_group_uuid" ON "menu_item_modifier_group" ("modifier_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_menu_menu_category_menu_category_uuid" ON "menu_menu_category" ("menu_category_uuid");

CREATE INDEX IF NOT EXISTS "idx_menu_menu_category_menu_uuid" ON "menu_menu_category" ("menu_uuid");

CREATE INDEX IF NOT EXISTS "idx_modifier_location_group_uuid" ON "modifier" ("location_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_modifier_group_location_group_uuid" ON "modifier_group" ("location_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_modifier_group_modifier_modifier_group_uuid" ON "modifier_group_modifier" ("modifier_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_modifier_group_modifier_modifier_uuid" ON "modifier_group_modifier" ("modifier_uuid");

CREATE INDEX IF NOT EXISTS "idx_promotion_location_group_uuid" ON "promotion" ("location_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_session_entity" ON "session" ("entity_uuid");

CREATE INDEX IF NOT EXISTS "idx_sub_category_location_group_uuid" ON "sub_category" ("location_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_sub_category_menu_category_uuid" ON "sub_category" ("menu_category_uuid");

CREATE INDEX IF NOT EXISTS "idx_sub_category_menu_item_menu_item_uuid" ON "sub_category_menu_item" ("menu_item_uuid");

CREATE INDEX IF NOT EXISTS "idx_sub_category_menu_item_sub_category_uuid" ON "sub_category_menu_item" ("sub_category_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticket_admin_uuid" ON "ticket" ("admin_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticket_fulfillment_uuid" ON "ticket" ("fulfillment_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticket_guest_address_uuid" ON "ticket" ("guest_address_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticket_guest_uuid" ON "ticket" ("guest_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticket_location_group_uuid" ON "ticket" ("location_group_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticket_table_uuid" ON "ticket" ("table_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticketlog_location_timestamp" ON "ticket_log" ("location_group_uuid", "time_stamp");

CREATE INDEX IF NOT EXISTS "idx_ticket_menu_item_menu_item_uuid" ON "ticket_menu_item" ("menu_item_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticket_menu_item_ticket_uuid" ON "ticket_menu_item" ("ticket_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticket_menu_item_modifier_modifier_uuid" ON "ticket_menu_item_modifier" ("modifier_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticket_menu_item_modifier_ticket_menu_item_uuid" ON "ticket_menu_item_modifier" ("ticket_menu_item_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticket_menu_item_modifier_ticket_uuid" ON "ticket_menu_item_modifier" ("ticket_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticket_payment_payment_uuid" ON "ticket_payment" ("payment_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticket_payment_ticket_uuid" ON "ticket_payment" ("ticket_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticket_promotion_promotion_uuid" ON "ticket_promotion" ("promotion_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticket_promotion_ticket_menu_item_uuid" ON "ticket_promotion" ("ticket_menu_item_uuid");

CREATE INDEX IF NOT EXISTS "idx_ticket_promotion_ticket_uuid" ON "ticket_promotion" ("ticket_uuid");`

export const SEED_ORDER: string[] = [
  'environment',
  'feature',
  'fulfillment',
  'guest',
  'guest_address',
  'guest_push_creds',
  'key_value',
  'language',
  'country',
  'lets_encrypt',
  'location_group',
  'combo',
  'dining_table',
  'guest_location_group',
  'location_group_activation_history',
  'location_group_feature',
  'location_group_schema_version',
  'log',
  'menu',
  'menu_category',
  'menu_combo',
  'menu_item',
  'bogo_menu_item',
  'combo_menu_item',
  'menu_item_menu_category',
  'menu_menu_category',
  'mock_schema_sync_probe',
  'modifier',
  'modifier_group',
  'menu_item_modifier_group',
  'modifier_group_modifier',
  'payment',
  'permission',
  'print_record',
  'printer_type',
  'location_group_printer',
  'admin',
  'admin_balance_history',
  'admin_location',
  'admin_location_permission',
  'admin_push_creds',
  'promotion',
  'session',
  'sub_category',
  'sub_category_menu_item',
  'ticket',
  'ticket_log',
  'ticket_log_applied',
  'ticket_menu_item',
  'ticket_menu_item_modifier',
  'ticket_payment',
  'ticket_print',
  'ticket_promotion',
]

// SQLite table → column schema: snake column → column def.
// Wire key == SQLite column name (one naming scheme, §5.5a).
export interface EngineColumn {
  name: string
  type: 'TEXT' | 'INTEGER' | 'REAL'
  nullable: boolean
  default?: string
}

export const SEED_COLUMNS: Record<string, Record<string, EngineColumn>> = {
  "admin": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "user_name": { name: "user_name", type: "TEXT", nullable: false },
    "first_name": { name: "first_name", type: "TEXT", nullable: true },
    "last_name": { name: "last_name", type: "TEXT", nullable: true },
    "email": { name: "email", type: "TEXT", nullable: true },
    "phone": { name: "phone", type: "TEXT", nullable: true },
    "password_hash": { name: "password_hash", type: "TEXT", nullable: false },
    "last_login_date_time": { name: "last_login_date_time", type: "TEXT", nullable: true },
    "login_tries": { name: "login_tries", type: "INTEGER", nullable: true, default: "0" },
    "mute": { name: "mute", type: "INTEGER", nullable: false, default: "true" },
    "time_stamp": { name: "time_stamp", type: "TEXT", nullable: true, default: "CURRENT_TIMESTAMP" },
    "silent_print": { name: "silent_print", type: "INTEGER", nullable: false, default: "false" },
    "kitchen_location_group_printer_uuid": { name: "kitchen_location_group_printer_uuid", type: "TEXT", nullable: true },
    "guest_location_group_printer_uuid": { name: "guest_location_group_printer_uuid", type: "TEXT", nullable: true },
    "is_owner": { name: "is_owner", type: "INTEGER", nullable: false, default: "false" },
  },
  "admin_balance_history": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "admin_uuid": { name: "admin_uuid", type: "TEXT", nullable: false },
    "time_stamp": { name: "time_stamp", type: "TEXT", nullable: true, default: "CURRENT_TIMESTAMP" },
    "balance_whole": { name: "balance_whole", type: "INTEGER", nullable: false, default: "0" },
    "balance_hundredths": { name: "balance_hundredths", type: "INTEGER", nullable: false, default: "0" },
    "add": { name: "add", type: "INTEGER", nullable: true, default: "true" },
    "confirmation_code": { name: "confirmation_code", type: "TEXT", nullable: true },
    "confirmed": { name: "confirmed", type: "INTEGER", nullable: true, default: "false" },
  },
  "admin_location": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "admin_uuid": { name: "admin_uuid", type: "TEXT", nullable: false },
    "owner": { name: "owner", type: "INTEGER", nullable: true, default: "false" },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
  },
  "admin_location_permission": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "admin_location_uuid": { name: "admin_location_uuid", type: "TEXT", nullable: false },
    "permission_uuid": { name: "permission_uuid", type: "TEXT", nullable: false },
  },
  "admin_push_creds": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "admin_uuid": { name: "admin_uuid", type: "TEXT", nullable: false },
    "endpoint": { name: "endpoint", type: "TEXT", nullable: false },
    "p256dh": { name: "p256dh", type: "TEXT", nullable: false },
    "auth": { name: "auth", type: "TEXT", nullable: false },
  },
  "bogo_menu_item": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "bogo_uuid": { name: "bogo_uuid", type: "TEXT", nullable: false },
    "menu_item_uuid": { name: "menu_item_uuid", type: "TEXT", nullable: false },
  },
  "combo": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "name": { name: "name", type: "TEXT", nullable: false },
    "description": { name: "description", type: "TEXT", nullable: true },
    "active": { name: "active", type: "INTEGER", nullable: true, default: "true" },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
    "price_whole": { name: "price_whole", type: "INTEGER", nullable: false },
    "price_hundredths": { name: "price_hundredths", type: "INTEGER", nullable: false },
  },
  "combo_menu_item": {
    "combo_uuid": { name: "combo_uuid", type: "TEXT", nullable: false },
    "menu_item_uuid": { name: "menu_item_uuid", type: "TEXT", nullable: false },
    "minimum_amount": { name: "minimum_amount", type: "INTEGER", nullable: false, default: "0" },
  },
  "country": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "nombre": { name: "nombre", type: "TEXT", nullable: false },
    "name": { name: "name", type: "TEXT", nullable: false },
    "iso2": { name: "iso2", type: "TEXT", nullable: false },
    "iso3": { name: "iso3", type: "TEXT", nullable: false },
    "phonecode": { name: "phonecode", type: "INTEGER", nullable: true },
    "language_uuid": { name: "language_uuid", type: "TEXT", nullable: true },
  },
  "dining_table": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "name": { name: "name", type: "TEXT", nullable: true },
    "active": { name: "active", type: "INTEGER", nullable: true },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
  },
  "environment": {
    "name": { name: "name", type: "TEXT", nullable: false },
  },
  "feature": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "name": { name: "name", type: "TEXT", nullable: false },
    "self_serve": { name: "self_serve", type: "INTEGER", nullable: false },
    "price_whole": { name: "price_whole", type: "INTEGER", nullable: false, default: "0" },
    "price_hundredths": { name: "price_hundredths", type: "INTEGER", nullable: false, default: "0" },
  },
  "fulfillment": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "name": { name: "name", type: "TEXT", nullable: false },
  },
  "guest": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "user_name": { name: "user_name", type: "TEXT", nullable: false },
    "first_name": { name: "first_name", type: "TEXT", nullable: true },
    "last_name": { name: "last_name", type: "TEXT", nullable: true },
    "email": { name: "email", type: "TEXT", nullable: true },
    "phone": { name: "phone", type: "TEXT", nullable: true },
    "password_hash": { name: "password_hash", type: "TEXT", nullable: true },
    "last_login_date_time": { name: "last_login_date_time", type: "TEXT", nullable: true },
    "login_tries": { name: "login_tries", type: "INTEGER", nullable: true, default: "0" },
  },
  "guest_address": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "address": { name: "address", type: "TEXT", nullable: false },
    "guest_uuid": { name: "guest_uuid", type: "TEXT", nullable: false },
  },
  "guest_location_group": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "guest_uuid": { name: "guest_uuid", type: "TEXT", nullable: false },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
    "points": { name: "points", type: "INTEGER", nullable: false, default: "0" },
  },
  "guest_push_creds": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "guest_uuid": { name: "guest_uuid", type: "TEXT", nullable: true },
    "app_unique_uuid": { name: "app_unique_uuid", type: "TEXT", nullable: true },
    "endpoint": { name: "endpoint", type: "TEXT", nullable: false },
    "p256dh": { name: "p256dh", type: "TEXT", nullable: false },
    "auth": { name: "auth", type: "TEXT", nullable: false },
  },
  "key_value": {
    "key": { name: "key", type: "TEXT", nullable: false },
    "value": { name: "value", type: "TEXT", nullable: false },
  },
  "language": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "name": { name: "name", type: "TEXT", nullable: false },
    "nombre": { name: "nombre", type: "TEXT", nullable: false },
  },
  "lets_encrypt": {
    "name": { name: "name", type: "TEXT", nullable: false },
  },
  "location_group": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "name": { name: "name", type: "TEXT", nullable: false },
    "description1": { name: "description1", type: "TEXT", nullable: true },
    "description2": { name: "description2", type: "TEXT", nullable: true },
    "description3": { name: "description3", type: "TEXT", nullable: true },
    "description4": { name: "description4", type: "TEXT", nullable: true },
    "url_name": { name: "url_name", type: "TEXT", nullable: true },
    "phone": { name: "phone", type: "TEXT", nullable: true },
    "address": { name: "address", type: "TEXT", nullable: true },
    "city": { name: "city", type: "TEXT", nullable: true },
    "ticket_description": { name: "ticket_description", type: "TEXT", nullable: true },
    "theme": { name: "theme", type: "INTEGER", nullable: false, default: "0" },
    "time_stamp": { name: "time_stamp", type: "TEXT", nullable: true, default: "CURRENT_TIMESTAMP" },
    "qr_code": { name: "qr_code", type: "TEXT", nullable: true },
    "tip_percentage": { name: "tip_percentage", type: "INTEGER", nullable: false, default: "0" },
    "country_uuid": { name: "country_uuid", type: "TEXT", nullable: false, default: "'e56e26df-5232-434d-ac1b-4cf1c3e48a9f'" },
    "day_price_cents": { name: "day_price_cents", type: "INTEGER", nullable: false, default: "17" },
    "simple_print": { name: "simple_print", type: "INTEGER", nullable: false, default: "true" },
    "print_notes": { name: "print_notes", type: "INTEGER", nullable: false, default: "true" },
    "tax_percentage": { name: "tax_percentage", type: "INTEGER", nullable: false, default: "0" },
  },
  "location_group_activation_history": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
    "time_stamp": { name: "time_stamp", type: "TEXT", nullable: true, default: "CURRENT_TIMESTAMP" },
    "active": { name: "active", type: "INTEGER", nullable: true, default: "true" },
    "day_price_cents": { name: "day_price_cents", type: "INTEGER", nullable: false, default: "17" },
  },
  "location_group_feature": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
    "feature_uuid": { name: "feature_uuid", type: "TEXT", nullable: false },
    "time_stamp": { name: "time_stamp", type: "TEXT", nullable: true, default: "CURRENT_TIMESTAMP" },
  },
  "location_group_printer": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "name": { name: "name", type: "TEXT", nullable: false },
    "address": { name: "address", type: "TEXT", nullable: false },
    "width_millimeters": { name: "width_millimeters", type: "INTEGER", nullable: false },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
    "printer_type_uuid": { name: "printer_type_uuid", type: "TEXT", nullable: false },
    "host": { name: "host", type: "TEXT", nullable: true },
    "port": { name: "port", type: "INTEGER", nullable: true },
  },
  "location_group_schema_version": {
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
    "version": { name: "version", type: "INTEGER", nullable: false, default: "1" },
    "updated_at": { name: "updated_at", type: "TEXT", nullable: false, default: "CURRENT_TIMESTAMP" },
  },
  "log": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "level": { name: "level", type: "TEXT", nullable: true },
    "id": { name: "id", type: "TEXT", nullable: true },
    "status": { name: "status", type: "TEXT", nullable: true },
    "req": { name: "req", type: "TEXT", nullable: true },
    "type": { name: "type", type: "TEXT", nullable: true },
    "path": { name: "path", type: "TEXT", nullable: true },
    "file": { name: "file", type: "TEXT", nullable: true },
    "data": { name: "data", type: "TEXT", nullable: true },
    "ms": { name: "ms", type: "TEXT", nullable: true },
  },
  "menu": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "name": { name: "name", type: "TEXT", nullable: false },
    "description": { name: "description", type: "TEXT", nullable: true },
    "active": { name: "active", type: "INTEGER", nullable: true, default: "true" },
    "sh0": { name: "sh0", type: "INTEGER", nullable: true },
    "sm0": { name: "sm0", type: "INTEGER", nullable: true },
    "st0": { name: "st0", type: "TEXT", nullable: true },
    "eh0": { name: "eh0", type: "INTEGER", nullable: true },
    "em0": { name: "em0", type: "INTEGER", nullable: true },
    "et0": { name: "et0", type: "TEXT", nullable: true },
    "sh1": { name: "sh1", type: "INTEGER", nullable: true },
    "sm1": { name: "sm1", type: "INTEGER", nullable: true },
    "st1": { name: "st1", type: "TEXT", nullable: true },
    "eh1": { name: "eh1", type: "INTEGER", nullable: true },
    "em1": { name: "em1", type: "INTEGER", nullable: true },
    "et1": { name: "et1", type: "TEXT", nullable: true },
    "sh2": { name: "sh2", type: "INTEGER", nullable: true },
    "sm2": { name: "sm2", type: "INTEGER", nullable: true },
    "st2": { name: "st2", type: "TEXT", nullable: true },
    "eh2": { name: "eh2", type: "INTEGER", nullable: true },
    "em2": { name: "em2", type: "INTEGER", nullable: true },
    "et2": { name: "et2", type: "TEXT", nullable: true },
    "sh3": { name: "sh3", type: "INTEGER", nullable: true },
    "sm3": { name: "sm3", type: "INTEGER", nullable: true },
    "st3": { name: "st3", type: "TEXT", nullable: true },
    "eh3": { name: "eh3", type: "INTEGER", nullable: true },
    "em3": { name: "em3", type: "INTEGER", nullable: true },
    "et3": { name: "et3", type: "TEXT", nullable: true },
    "sh4": { name: "sh4", type: "INTEGER", nullable: true },
    "sm4": { name: "sm4", type: "INTEGER", nullable: true },
    "st4": { name: "st4", type: "TEXT", nullable: true },
    "eh4": { name: "eh4", type: "INTEGER", nullable: true },
    "em4": { name: "em4", type: "INTEGER", nullable: true },
    "et4": { name: "et4", type: "TEXT", nullable: true },
    "sh5": { name: "sh5", type: "INTEGER", nullable: true },
    "sm5": { name: "sm5", type: "INTEGER", nullable: true },
    "st5": { name: "st5", type: "TEXT", nullable: true },
    "eh5": { name: "eh5", type: "INTEGER", nullable: true },
    "em5": { name: "em5", type: "INTEGER", nullable: true },
    "et5": { name: "et5", type: "TEXT", nullable: true },
    "sh6": { name: "sh6", type: "INTEGER", nullable: true },
    "sm6": { name: "sm6", type: "INTEGER", nullable: true },
    "st6": { name: "st6", type: "TEXT", nullable: true },
    "eh6": { name: "eh6", type: "INTEGER", nullable: true },
    "em6": { name: "em6", type: "INTEGER", nullable: true },
    "et6": { name: "et6", type: "TEXT", nullable: true },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
  },
  "menu_category": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "name": { name: "name", type: "TEXT", nullable: false },
    "description": { name: "description", type: "TEXT", nullable: true },
    "active": { name: "active", type: "INTEGER", nullable: true, default: "true" },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
  },
  "menu_combo": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "menu_uuid": { name: "menu_uuid", type: "TEXT", nullable: false },
    "combo_uuid": { name: "combo_uuid", type: "TEXT", nullable: false },
  },
  "menu_item": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "name": { name: "name", type: "TEXT", nullable: true },
    "description": { name: "description", type: "TEXT", nullable: true },
    "active": { name: "active", type: "INTEGER", nullable: true, default: "true" },
    "complete": { name: "complete", type: "INTEGER", nullable: true, default: "false" },
    "price_whole": { name: "price_whole", type: "INTEGER", nullable: false },
    "price_hundredths": { name: "price_hundredths", type: "INTEGER", nullable: false },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
    "cache": { name: "cache", type: "TEXT", nullable: false },
  },
  "menu_item_menu_category": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "menu_item_uuid": { name: "menu_item_uuid", type: "TEXT", nullable: false },
    "menu_category_uuid": { name: "menu_category_uuid", type: "TEXT", nullable: false },
  },
  "menu_item_modifier_group": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "modifier_group_uuid": { name: "modifier_group_uuid", type: "TEXT", nullable: false },
    "menu_item_uuid": { name: "menu_item_uuid", type: "TEXT", nullable: false },
  },
  "menu_menu_category": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "menu_uuid": { name: "menu_uuid", type: "TEXT", nullable: false },
    "menu_category_uuid": { name: "menu_category_uuid", type: "TEXT", nullable: false },
  },
  "mock_schema_sync_probe": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "label": { name: "label", type: "TEXT", nullable: true },
    "created_at": { name: "created_at", type: "TEXT", nullable: false, default: "CURRENT_TIMESTAMP" },
  },
  "modifier": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "name": { name: "name", type: "TEXT", nullable: false },
    "description": { name: "description", type: "TEXT", nullable: true },
    "active": { name: "active", type: "INTEGER", nullable: true, default: "true" },
    "price_whole": { name: "price_whole", type: "INTEGER", nullable: false, default: "0" },
    "price_hundredths": { name: "price_hundredths", type: "INTEGER", nullable: false, default: "0" },
    "limit": { name: "limit", type: "INTEGER", nullable: false, default: "0" },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
  },
  "modifier_group": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "amount_required": { name: "amount_required", type: "INTEGER", nullable: false },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
  },
  "modifier_group_modifier": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "modifier_group_uuid": { name: "modifier_group_uuid", type: "TEXT", nullable: false },
    "modifier_uuid": { name: "modifier_uuid", type: "TEXT", nullable: false },
  },
  "payment": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "name": { name: "name", type: "TEXT", nullable: false },
  },
  "permission": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "name": { name: "name", type: "TEXT", nullable: false },
  },
  "print_record": {
    "ticket_uuid": { name: "ticket_uuid", type: "TEXT", nullable: false },
    "decision": { name: "decision", type: "TEXT", nullable: false, default: "'pending'" },
    "printed_at": { name: "printed_at", type: "INTEGER", nullable: true },
    "synced": { name: "synced", type: "INTEGER", nullable: false, default: "0" },
  },
  "printer_type": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "type": { name: "type", type: "TEXT", nullable: false },
  },
  "promotion": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "type": { name: "type", type: "TEXT", nullable: false },
    "active": { name: "active", type: "INTEGER", nullable: false, default: "true" },
    "name": { name: "name", type: "TEXT", nullable: false },
    "description": { name: "description", type: "TEXT", nullable: true },
    "auto_apply": { name: "auto_apply", type: "INTEGER", nullable: false, default: "true" },
    "promotion_is_percentage": { name: "promotion_is_percentage", type: "INTEGER", nullable: false, default: "false" },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
    "discount_percent": { name: "discount_percent", type: "INTEGER", nullable: true },
    "discount_whole": { name: "discount_whole", type: "INTEGER", nullable: true },
    "discount_hundredths": { name: "discount_hundredths", type: "INTEGER", nullable: true },
    "points_required": { name: "points_required", type: "INTEGER", nullable: true },
    "points_earnable": { name: "points_earnable", type: "INTEGER", nullable: true },
    "points_multiplier": { name: "points_multiplier", type: "INTEGER", nullable: false, default: "0" },
    "items_required": { name: "items_required", type: "INTEGER", nullable: true },
    "minimum_purchase_whole": { name: "minimum_purchase_whole", type: "INTEGER", nullable: true },
    "minimum_purchase_hundredths": { name: "minimum_purchase_hundredths", type: "INTEGER", nullable: true },
    "bogo_buy": { name: "bogo_buy", type: "TEXT", nullable: true },
    "bogo_buy_items_ammount": { name: "bogo_buy_items_ammount", type: "INTEGER", nullable: true },
    "bogo_get": { name: "bogo_get", type: "TEXT", nullable: true },
    "bogo_get_items_ammount": { name: "bogo_get_items_ammount", type: "INTEGER", nullable: true },
    "all_week": { name: "all_week", type: "INTEGER", nullable: false, default: "true" },
    "mon": { name: "mon", type: "INTEGER", nullable: false, default: "false" },
    "tue": { name: "tue", type: "INTEGER", nullable: false, default: "false" },
    "wed": { name: "wed", type: "INTEGER", nullable: false, default: "false" },
    "thu": { name: "thu", type: "INTEGER", nullable: false, default: "false" },
    "fri": { name: "fri", type: "INTEGER", nullable: false, default: "false" },
    "sat": { name: "sat", type: "INTEGER", nullable: false, default: "false" },
    "sun": { name: "sun", type: "INTEGER", nullable: false, default: "false" },
    "monday_start_time": { name: "monday_start_time", type: "INTEGER", nullable: true },
    "monday_end_time": { name: "monday_end_time", type: "INTEGER", nullable: true },
    "tuesday_start_time": { name: "tuesday_start_time", type: "INTEGER", nullable: true },
    "tuesday_end_time": { name: "tuesday_end_time", type: "INTEGER", nullable: true },
    "wednesday_start_time": { name: "wednesday_start_time", type: "INTEGER", nullable: true },
    "wednesday_end_time": { name: "wednesday_end_time", type: "INTEGER", nullable: true },
    "thursday_start_time": { name: "thursday_start_time", type: "INTEGER", nullable: true },
    "thursday_end_time": { name: "thursday_end_time", type: "INTEGER", nullable: true },
    "friday_start_time": { name: "friday_start_time", type: "INTEGER", nullable: true },
    "friday_end_time": { name: "friday_end_time", type: "INTEGER", nullable: true },
    "saturday_start_time": { name: "saturday_start_time", type: "INTEGER", nullable: true },
    "saturday_end_time": { name: "saturday_end_time", type: "INTEGER", nullable: true },
    "sunday_start_time": { name: "sunday_start_time", type: "INTEGER", nullable: true },
    "sunday_end_time": { name: "sunday_end_time", type: "INTEGER", nullable: true },
    "redeemptions_per_visit": { name: "redeemptions_per_visit", type: "INTEGER", nullable: true },
    "redeemptions_per_day": { name: "redeemptions_per_day", type: "INTEGER", nullable: true },
    "redeemptions_per_week": { name: "redeemptions_per_week", type: "INTEGER", nullable: true },
    "redeemptions_per_month": { name: "redeemptions_per_month", type: "INTEGER", nullable: true },
    "redeemptions_all_time": { name: "redeemptions_all_time", type: "INTEGER", nullable: true },
    "minimum_total_tickets": { name: "minimum_total_tickets", type: "INTEGER", nullable: true },
    "combinable": { name: "combinable", type: "INTEGER", nullable: false, default: "false" },
    "all_items": { name: "all_items", type: "INTEGER", nullable: false, default: "true" },
    "all_categories": { name: "all_categories", type: "INTEGER", nullable: false, default: "true" },
    "itemless": { name: "itemless", type: "INTEGER", nullable: false, default: "false" },
  },
  "session": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "entity_uuid": { name: "entity_uuid", type: "TEXT", nullable: false },
    "entity_type": { name: "entity_type", type: "TEXT", nullable: false },
    "time_stamp": { name: "time_stamp", type: "TEXT", nullable: true, default: "CURRENT_TIMESTAMP" },
    "expires_at": { name: "expires_at", type: "TEXT", nullable: false },
  },
  "sub_category": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "name": { name: "name", type: "TEXT", nullable: false },
    "description": { name: "description", type: "TEXT", nullable: true },
    "parent_uuid": { name: "parent_uuid", type: "TEXT", nullable: false },
    "menu_category_uuid": { name: "menu_category_uuid", type: "TEXT", nullable: false },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
  },
  "sub_category_menu_item": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "sub_category_uuid": { name: "sub_category_uuid", type: "TEXT", nullable: false },
    "menu_item_uuid": { name: "menu_item_uuid", type: "TEXT", nullable: false },
  },
  "ticket": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "id": { name: "id", type: "INTEGER", nullable: false },
    "time_stamp": { name: "time_stamp", type: "TEXT", nullable: true, default: "CURRENT_TIMESTAMP" },
    "status": { name: "status", type: "TEXT", nullable: true },
    "guest_uuid": { name: "guest_uuid", type: "TEXT", nullable: true },
    "app_unique_uuid": { name: "app_unique_uuid", type: "TEXT", nullable: true },
    "table_uuid": { name: "table_uuid", type: "TEXT", nullable: true },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
    "fulfillment_uuid": { name: "fulfillment_uuid", type: "TEXT", nullable: true },
    "guest_address_uuid": { name: "guest_address_uuid", type: "TEXT", nullable: true },
    "admin_uuid": { name: "admin_uuid", type: "TEXT", nullable: true },
    "anonymous_address": { name: "anonymous_address", type: "TEXT", nullable: true },
    "price_whole": { name: "price_whole", type: "INTEGER", nullable: true },
    "price_hundredths": { name: "price_hundredths", type: "INTEGER", nullable: true },
    "is_dirty": { name: "is_dirty", type: "INTEGER", nullable: false, default: "false" },
    "is_local": { name: "is_local", type: "INTEGER", nullable: false, default: "false" },
  },
  "ticket_log": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "location_group_uuid": { name: "location_group_uuid", type: "TEXT", nullable: false },
    "ticket_uuid": { name: "ticket_uuid", type: "TEXT", nullable: false },
    "action": { name: "action", type: "TEXT", nullable: false },
    "payload": { name: "payload", type: "TEXT", nullable: false },
    "time_stamp": { name: "time_stamp", type: "INTEGER", nullable: false },
    "admin_uuid": { name: "admin_uuid", type: "TEXT", nullable: true },
  },
  "ticket_log_applied": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "time_stamp": { name: "time_stamp", type: "TEXT", nullable: true },
    "retry_count": { name: "retry_count", type: "INTEGER", nullable: true, default: "0" },
    "last_error": { name: "last_error", type: "TEXT", nullable: true },
    "next_retry_at": { name: "next_retry_at", type: "INTEGER", nullable: true },
  },
  "ticket_menu_item": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "ticket_uuid": { name: "ticket_uuid", type: "TEXT", nullable: false },
    "menu_item_uuid": { name: "menu_item_uuid", type: "TEXT", nullable: false },
    "note": { name: "note", type: "TEXT", nullable: true },
  },
  "ticket_menu_item_modifier": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "ticket_uuid": { name: "ticket_uuid", type: "TEXT", nullable: false },
    "modifier_uuid": { name: "modifier_uuid", type: "TEXT", nullable: false },
    "ticket_menu_item_uuid": { name: "ticket_menu_item_uuid", type: "TEXT", nullable: false },
    "time_stamp": { name: "time_stamp", type: "TEXT", nullable: true, default: "CURRENT_TIMESTAMP" },
  },
  "ticket_payment": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "ticket_uuid": { name: "ticket_uuid", type: "TEXT", nullable: false },
    "payment_uuid": { name: "payment_uuid", type: "TEXT", nullable: false },
    "price_whole": { name: "price_whole", type: "INTEGER", nullable: false },
    "price_hundredths": { name: "price_hundredths", type: "INTEGER", nullable: false },
    "code": { name: "code", type: "TEXT", nullable: true },
    "complete": { name: "complete", type: "INTEGER", nullable: true, default: "false" },
  },
  "ticket_print": {
    "ticket_uuid": { name: "ticket_uuid", type: "TEXT", nullable: false },
    "claimed_at": { name: "claimed_at", type: "TEXT", nullable: true },
    "printed_at": { name: "printed_at", type: "TEXT", nullable: true },
    "claimed_by": { name: "claimed_by", type: "TEXT", nullable: true },
  },
  "ticket_promotion": {
    "uuid": { name: "uuid", type: "TEXT", nullable: false },
    "time_stamp": { name: "time_stamp", type: "TEXT", nullable: true, default: "CURRENT_TIMESTAMP" },
    "ticket_uuid": { name: "ticket_uuid", type: "TEXT", nullable: false },
    "promotion_uuid": { name: "promotion_uuid", type: "TEXT", nullable: false },
    "ticket_menu_item_uuid": { name: "ticket_menu_item_uuid", type: "TEXT", nullable: true },
  },
}
